/**
 * Home Assistant Configuration Generator for SpoolmanSync
 *
 * Generates automations.yaml and configuration.yaml additions
 * for automatic spool tracking with Bambu Lab printers.
 */

import { HAPrinter } from './api/homeassistant';

export interface GeneratedConfig {
  automationsYaml: string;
  configurationAdditions: string;
  printerCount: number;
  trayCount: number;
}

/**
 * Generate complete HA configuration for SpoolmanSync
 */
export function generateHAConfig(
  printers: HAPrinter[],
  webhookUrl: string,
  spoolmanUrl: string
): GeneratedConfig {
  if (printers.length === 0) {
    return {
      automationsYaml: '[]',
      configurationAdditions: '',
      printerCount: 0,
      trayCount: 0,
    };
  }

  // For now, use the first printer (most users have one)
  // TODO: Support multiple printers
  const printer = printers[0];
  const prefix = extractPrinterPrefix(printer.entity_id);

  // Count total trays
  let trayCount = 0;
  for (const ams of printer.ams_units) {
    trayCount += ams.trays.length;
  }
  if (printer.external_spool) {
    trayCount++;
  }

  // Determine tray entity suffix (newer versions use _2)
  const traySuffix = determineTrayEntitySuffix(printer);

  // Determine external spool entity ID (if exists)
  const externalSpoolEntityId = printer.external_spool?.entity_id || null;

  // Generate the comprehensive automation
  const automationsYaml = generateAutomationsYaml(prefix, traySuffix, webhookUrl, externalSpoolEntityId);

  // Generate configuration additions
  const configurationAdditions = generateConfigurationAdditions(prefix, traySuffix, spoolmanUrl, externalSpoolEntityId);

  return {
    automationsYaml,
    configurationAdditions,
    printerCount: printers.length,
    trayCount,
  };
}

/**
 * Extract printer prefix from entity ID
 * e.g., "sensor.x1c_00m09d462101575_print_status" -> "x1c_00m09d462101575"
 */
function extractPrinterPrefix(entityId: string): string {
  const match = entityId.match(/sensor\.(.+)_print_status$/);
  return match ? match[1] : entityId.replace('sensor.', '').replace('_print_status', '');
}

/**
 * Extract the entity suffix from tray entities (e.g., _2, _3, etc.)
 * Newer ha-bambulab versions create entities with suffixes when re-added
 */
function determineTrayEntitySuffix(printer: HAPrinter): string {
  if (printer.ams_units.length > 0 && printer.ams_units[0].trays.length > 0) {
    const trayEntityId = printer.ams_units[0].trays[0].entity_id;
    // Match entity suffix pattern: sensor.xxx_ams_1_tray_1_2 -> _2
    // Pattern: ends with _tray_N or _tray_N_S where N is tray number and S is suffix
    const match = trayEntityId.match(/_tray_\d+(_\d+)?$/);
    if (match && match[1]) {
      return match[1]; // Returns _2, _3, etc.
    }
    return ''; // No suffix
  }
  return '_2'; // Default to newer format
}

/**
 * Generate automations.yaml content based on working template
 * Supports both AMS trays (1-4) and external spool (tray 0)
 */
function generateAutomationsYaml(prefix: string, traySuffix: string, webhookUrl: string, externalSpoolEntityId: string | null): string {
  // Build the tray_sensor variable logic - handles both AMS trays and external spool
  const traySensorLogic = externalSpoolEntityId
    ? `{% if tray_number == 0 %}${externalSpoolEntityId}{% else %}sensor.${prefix}_ams_1_tray_{{ tray_number }}${traySuffix}{% endif %}`
    : `sensor.${prefix}_ams_1_tray_{{ tray_number }}${traySuffix}`;

  return `# =============================================================================
# SpoolmanSync Automation: Track Spool Usage
#
# Auto-generated by SpoolmanSync for printer: ${prefix}
#
# This automation tracks:
# 1. Tray changes - when the AMS switches to a different tray (or external spool)
# 2. Print completion - to log final filament usage
# =============================================================================
- id: 'spoolmansync_update_spool_${prefix}'
  alias: SpoolmanSync - Update Spool
  description: Track spool usage and sync with Spoolman
  triggers:
    - entity_id: sensor.spoolmansync_${prefix}_active_tray
      id: tray
      trigger: state
    - entity_id: sensor.${prefix}_current_stage
      to:
        - finished
        - idle
      id: print_end
      trigger: state
  variables:
    # For tray trigger: get the old tray number (what we're switching FROM)
    # Tray 0 = external spool, Trays 1-4 = AMS trays
    old_tray: |-
      {% if trigger.id == 'tray' and trigger.from_state.state not in [None, '', 'unknown', 'unavailable'] %}
        {{ trigger.from_state.state | int(-1) }}
      {% else %}
        -1
      {% endif %}
    # For tray trigger: get the new tray number (what we're switching TO)
    new_tray: |-
      {% if trigger.id == 'tray' and trigger.to_state.state not in [None, '', 'unknown', 'unavailable'] %}
        {{ trigger.to_state.state | int(-1) }}
      {% else %}
        -1
      {% endif %}
    # For print_end: use the helper
    tray_number: |-
      {% if trigger.id == 'print_end' %}
        {{ states('input_number.spoolmansync_last_tray') | int(-1) }}
      {% else %}
        {{ old_tray }}
      {% endif %}
    # Build sensor entity ID for the tray we're logging (0 = external spool, 1-4 = AMS)
    tray_sensor: "${traySensorLogic}"
    tray_weight: "{{ states('sensor.spoolmansync_filament_usage_meter') | float(0) | round(2) }}"
    tag_uid: "{{ state_attr(tray_sensor, 'tag_uid') | default('') }}"
    material: "{{ state_attr(tray_sensor, 'type') | default('') }}"
    name: "{{ state_attr(tray_sensor, 'name') | default('') }}"
    color: "{{ state_attr(tray_sensor, 'color') | default('') }}"
  actions:
    - choose:
        # =====================================================================
        # TRAY CHANGE - Log old tray usage (if valid), ALWAYS update helper
        # =====================================================================
        - conditions:
            - condition: template
              value_template: "{{ trigger.id == 'tray' }}"
          sequence:
            # Log usage from OLD tray only if it was valid and we have weight
            # old_tray >= 0 allows external spool (0) and AMS trays (1-4)
            - choose:
                - conditions:
                    - condition: template
                      value_template: "{{ old_tray >= 0 and tray_weight >= 0.01 }}"
                  sequence:
                    - action: system_log.write
                      data:
                        message: >-
                          SPOOLMANSYNC TRAY CHANGE | Old tray {{ old_tray }} -> New tray {{ new_tray }} |
                          Spool: {{ name }} ({{ material }}) |
                          Weight used: {{ tray_weight }}g |
                          Tag UID: {{ tag_uid }}
                        level: info
                    - action: rest_command.spoolmansync_update_spool
                      data:
                        filament_name: "{{ name }}"
                        filament_material: "{{ material }}"
                        filament_tag_uid: "{{ tag_uid }}"
                        filament_used_weight: "{{ tray_weight }}"
                        filament_color: "{{ color }}"
                        filament_active_tray_id: "{{ tray_sensor | replace('sensor.', '') }}"
                    - action: utility_meter.calibrate
                      target:
                        entity_id: sensor.spoolmansync_filament_usage_meter
                      data:
                        value: "0"
              default:
                - action: system_log.write
                  data:
                    message: >-
                      SPOOLMANSYNC TRAY CHANGE (no usage logged) | Old: {{ old_tray }} -> New: {{ new_tray }} |
                      Weight: {{ tray_weight }}g | Reason: {{ 'old_tray invalid' if old_tray < 0 else 'no weight' }}
                    level: debug
            # ALWAYS update helper to new tray (0 = external spool, 1-4 = AMS)
            - condition: template
              value_template: "{{ new_tray >= 0 }}"
            - action: input_number.set_value
              target:
                entity_id: input_number.spoolmansync_last_tray
              data:
                value: "{{ new_tray }}"
            - action: system_log.write
              data:
                message: "SPOOLMANSYNC HELPER UPDATED | input_number.spoolmansync_last_tray -> {{ new_tray }}"
                level: info

        # =====================================================================
        # PRINT END - Log final tray usage from helper
        # =====================================================================
        - conditions:
            - condition: template
              value_template: >-
                {{ trigger.id == 'print_end'
                   and trigger.from_state.state not in ['unavailable', 'unknown', 'idle', 'finished'] }}
          sequence:
            # tray_number >= 0 allows external spool (0) and AMS trays (1-4)
            - choose:
                - conditions:
                    - condition: template
                      value_template: "{{ tray_number >= 0 and tray_weight >= 0.01 }}"
                  sequence:
                    - action: system_log.write
                      data:
                        message: >-
                          SPOOLMANSYNC PRINT END | Tray {{ tray_number }} |
                          Spool: {{ name }} ({{ material }}) |
                          Weight used: {{ tray_weight }}g |
                          Tag UID: {{ tag_uid }}
                        level: info
                    - action: rest_command.spoolmansync_update_spool
                      data:
                        filament_name: "{{ name }}"
                        filament_material: "{{ material }}"
                        filament_tag_uid: "{{ tag_uid }}"
                        filament_used_weight: "{{ tray_weight }}"
                        filament_color: "{{ color }}"
                        filament_active_tray_id: "{{ tray_sensor | replace('sensor.', '') }}"
              default:
                - action: system_log.write
                  data:
                    message: >-
                      SPOOLMANSYNC PRINT END (skipped) | Tray: {{ tray_number }} | Weight: {{ tray_weight }}g |
                      Reason: {{ 'no tray in helper' if tray_number < 0 else 'no weight' }}
                    level: warning
            # Always reset meter after print
            - action: utility_meter.calibrate
              target:
                entity_id: sensor.spoolmansync_filament_usage_meter
              data:
                value: "0"
            - action: system_log.write
              data:
                message: "SPOOLMANSYNC METER RESET after print end"
                level: info
  mode: single
`;
}

/**
 * Generate configuration.yaml additions
 * Supports both AMS trays (1-4) and external spool (tray 0)
 */
function generateConfigurationAdditions(prefix: string, traySuffix: string, spoolmanUrl: string, externalSpoolEntityId: string | null): string {
  // Build the active tray detection logic - handles both AMS trays and external spool
  const externalSpoolCheck = externalSpoolEntityId
    ? `
          {# Check external spool first (tray 0) #}
          {% if state_attr('${externalSpoolEntityId}', 'active') in [true, 'true', 'True'] %}
            0
          {% else %}`
    : '';

  const externalSpoolCheckEnd = externalSpoolEntityId ? '{% endif %}' : '';

  // Build availability check including external spool if present
  const availabilityEntities = [
    `'sensor.${prefix}_ams_1_tray_1${traySuffix}'`,
    `'sensor.${prefix}_ams_1_tray_2${traySuffix}'`,
    `'sensor.${prefix}_ams_1_tray_3${traySuffix}'`,
    `'sensor.${prefix}_ams_1_tray_4${traySuffix}'`,
  ];
  if (externalSpoolEntityId) {
    availabilityEntities.push(`'${externalSpoolEntityId}'`);
  }

  return `
# =============================================================================
# SpoolmanSync Configuration
# Auto-generated for printer: ${prefix}
# =============================================================================

# Helper to track last active tray (captures tray when it changes)
# 0 = external spool, 1-4 = AMS trays
input_number:
  spoolmansync_last_tray:
    name: "SpoolmanSync Last Tray"
    min: 0
    max: 5
    step: 1

# Utility meter to track filament usage between updates
utility_meter:
  spoolmansync_filament_usage_meter:
    unique_id: spoolmansync-filament-usage-meter
    source: sensor.spoolmansync_filament_usage
    cycle: weekly

# REST command to send updates to SpoolmanSync webhook
rest_command:
  spoolmansync_update_spool:
    url: "${spoolmanUrl}"
    method: POST
    headers:
      Content-Type: "application/json"
    payload: >
      {
        "event": "spool_usage",
        "name": "{{ filament_name }}",
        "material": "{{ filament_material }}",
        "tag_uid": "{{ filament_tag_uid }}",
        "used_weight": {{ filament_used_weight | int }},
        "color": "{{ filament_color }}",
        "active_tray_id": "{{ filament_active_tray_id }}"
      }

# Template sensors for filament tracking
template:
  - sensor:
      # Calculate filament usage during print
      - name: "SpoolmanSync Filament Usage"
        unique_id: spoolmansync-filament-usage
        state: >
          {{ states('sensor.${prefix}_print_weight') | float(0) / 100 *
             states('sensor.${prefix}_print_progress') | float(0) }}
        availability: >
          {{ states('sensor.${prefix}_print_weight') not in ['unknown', 'unavailable'] }}

      # Detect active tray from AMS tray sensors or external spool
      # Returns: 0 = external spool, 1-4 = AMS trays
      - name: "SpoolmanSync ${prefix} Active Tray"
        unique_id: spoolmansync-${prefix}-active-tray
        state: >${externalSpoolCheck}
          {# Check AMS trays 1-4 #}
          {% set trays = [1,2,3,4] %}
          {% for tray in trays %}
            {% set eid = 'sensor.${prefix}_ams_1_tray_' ~ tray ~ '${traySuffix}' %}
            {% if state_attr(eid, 'active') in [true, 'true', 'True'] %}
              {{ tray }}
            {% endif %}
          {% endfor %}${externalSpoolCheckEnd}
        availability: >
          {{ expand([
            ${availabilityEntities.join(',\n            ')}
          ]) | selectattr('attributes.active','defined') | list | count > 0 }}
`;
}

/**
 * Merge configuration additions into existing configuration.yaml content
 */
export function mergeConfiguration(existingConfig: string, additions: string): string {
  // Check if SpoolmanSync config already exists
  if (existingConfig.includes('# SpoolmanSync Configuration')) {
    // Remove existing SpoolmanSync section and add new one
    const spoolmanSyncStart = existingConfig.indexOf('# =============================================================================\n# SpoolmanSync Configuration');
    if (spoolmanSyncStart !== -1) {
      // Find the end of the SpoolmanSync section (next major section or end of file)
      let spoolmanSyncEnd = existingConfig.length;
      const nextSection = existingConfig.indexOf('\n# ===', spoolmanSyncStart + 10);
      if (nextSection !== -1 && !existingConfig.substring(spoolmanSyncStart, nextSection).includes('SpoolmanSync')) {
        spoolmanSyncEnd = nextSection;
      }
      existingConfig = existingConfig.substring(0, spoolmanSyncStart) + existingConfig.substring(spoolmanSyncEnd);
    }
  }

  // Append the new configuration
  return existingConfig.trim() + '\n' + additions;
}
